title: Lets Go To India
author: Parichay Mazumdar and Imke Ditters
email: imke_parichay@protonmail.com
description: >
  Welcome to the info page for your trip to India for our wedding.

paginate: 10
paginate_path: "/blog/page:num/"
show_excerpts: true

markdown: kramdown
usemathjax: true

# theme: minima
remote_theme: cnorick/jekyll-theme-easy-wedding

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - drafts/
