title: Lets Go To India
author: Parichay Mazumdar and Imke Ditters
email: imke_parichay@protonmail.com
description: >
  Welcome to the info page for your trip to India for our wedding.

url: "https://imkeandparryinindia.com"

paginate: true
paginate_path: "/blog/page:num/"
show_excerpts: true

markdown: kramdown
usemathjax: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
